import { GLOBALS } from '../../../core/src';

export const BADGE_SCOPE_NAME = 'Badge';

export const BADGE_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${BADGE_SCOPE_NAME}`;
export const BADGE_LABEL_CLASSNAME = `${BADGE_ROOT_CLASSNAME}-label`;
export const BADGE_ICON_CLASSNAME = `${BADGE_ROOT_CLASSNAME}-icon`;
export const BADGE_ICON_START_CLASSNAME = `${BADGE_ICON_CLASSNAME}-start`;
export const BADGE_ICON_END_CLASSNAME = `${BADGE_ICON_CLASSNAME}-end`;
