export const BADGE_SCOPE_NAME = 'Badge';

export const BADGE_ROOT_CLASSNAME = BADGE_SCOPE_NAME;
export const BADGE_LABEL_CLASSNAME = `${BADGE_ROOT_CLASSNAME}-label`;
export const BADGE_ICON_CLASSNAME = `${BADGE_ROOT_CLASSNAME}-icon`;
export const BADGE_ICON_START_CLASSNAME = `${BADGE_ICON_CLASSNAME}-start`;
export const BADGE_ICON_END_CLASSNAME = `${BADGE_ICON_CLASSNAME}-end`;
