import { GLOBALS } from '../../../core/src';

export const CONTAINER_SCOPE_NAME = 'Container';

export const CONTAINER_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CONTAINER_SCOPE_NAME}`;
export const CONTAINER_FLUID_CLASSNAME = `${CONTAINER_ROOT_CLASSNAME}--fluid`;

export const CONTAINER_DEFAULT_ELEMENT_TYPE = 'div';
export const CONTAINER_DEFAULT_MAX_WIDTH = 'fluid';
