import { GLOBALS } from '../../../core/src';

export const CHECKBOX_SCOPE_NAME = 'Checkbox';
export const CHECKBOX_ELEMENT_SCOPE_NAME = `${CHECKBOX_SCOPE_NAME}Element`;
export const CHECKBOX_GROUP_SCOPE_NAME = `${CHECKBOX_SCOPE_NAME}Group`;

export const CHECKBOX_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_SCOPE_NAME}`;
export const CHECKBOX_ELEMENT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_ELEMENT_SCOPE_NAME}`;
export const CHECKBOX_LABEL_CLASSNAME = `${CHECKBOX_ROOT_CLASSNAME}-label`;
export const CHECKBOX_GROUP_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_GROUP_SCOPE_NAME}`;
export const CHECKBOX_GROUP_LABEL_CLASSNAME = `${CHECKBOX_GROUP_CLASSNAME}-label`;
export const CHECKBOX_GROUP_BODY_CLASSNAME = `${CHECKBOX_GROUP_CLASSNAME}-body`;
