import { GLOBALS } from '../../../core/src';

export const CHECKBOX_SCOPE_NAME = 'Checkbox';
export const CHECKBOX_BASE_SCOPE_NAME = `${CHECKBOX_SCOPE_NAME}Base`;
export const CHECKBOX_GROUP_SCOPE_NAME = `${CHECKBOX_SCOPE_NAME}Group`;

export const CHECKBOX_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_SCOPE_NAME}`;
export const CHECKBOX_BASE_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_BASE_SCOPE_NAME}`;
export const CHECKBOX_LABEL_CLASSNAME = `${CHECKBOX_ROOT_CLASSNAME}-label`;
export const CHECKBOX_GROUP_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_GROUP_SCOPE_NAME}`;
export const CHECKBOX_GROUP_LEGEND_CLASSNAME = `${CHECKBOX_GROUP_CLASSNAME}-legend`;
export const CHECKBOX_GROUP_BODY_CLASSNAME = `${CHECKBOX_GROUP_CLASSNAME}-body`;
