import { GLOBALS } from '../../../core/src';

export const CHECKBOX_SCOPE_NAME = 'Checkbox';
export const CHECKBOX_ELEMENT_SCOPE_NAME = `${CHECKBOX_SCOPE_NAME}Element`;

export const CHECKBOX_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_SCOPE_NAME}`;
export const CHECKBOX_ELEMENT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${CHECKBOX_ELEMENT_SCOPE_NAME}`;
export const CHECKBOX_LABEL_CLASSNAME = `${CHECKBOX_ROOT_CLASSNAME}-label`;
