import { GLOBALS } from '../../../core/src';

export const SWITCH_SCOPE_NAME = 'Switch';
export const SWITCH_BASE_SCOPE_NAME = `${SWITCH_SCOPE_NAME}Base`;
export const SWITCH_GROUP_SCOPE_NAME = `${SWITCH_SCOPE_NAME}Group`;

export const SWITCH_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${SWITCH_SCOPE_NAME}`;
export const SWITCH_BASE_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${SWITCH_BASE_SCOPE_NAME}`;
export const SWITCH_LABEL_CLASSNAME = `${SWITCH_ROOT_CLASSNAME}-label`;
export const SWITCH_GROUP_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${SWITCH_GROUP_SCOPE_NAME}`;
export const SWITCH_GROUP_LEGEND_CLASSNAME = `${SWITCH_GROUP_CLASSNAME}-legend`;
export const SWITCH_GROUP_BODY_CLASSNAME = `${SWITCH_GROUP_CLASSNAME}-body`;
