import { GLOBALS } from '../../../core/src';

export const SELECT_SCOPE_NAME = 'Select';
export const SELECT_BASE_SCOPE_NAME = `${SELECT_SCOPE_NAME}Base`;
export const OPTION_ITEM_SCOPE_NAME = 'OptionItem';
export const OPTION_GROUP_SCOPE_NAME = 'OptionGroup';

export const SELECT_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${SELECT_SCOPE_NAME}`;
export const SELECT_BASE_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${SELECT_BASE_SCOPE_NAME}`;
export const OPTION_ITEM_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${OPTION_ITEM_SCOPE_NAME}`;
export const OPTION_GROUP_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${OPTION_GROUP_SCOPE_NAME}`;
