import { GLOBALS } from '../../../core/src';

export const RADIO_SCOPE_NAME = 'Radio';
export const RADIO_BASE_SCOPE_NAME = `${RADIO_SCOPE_NAME}Element`;
export const RADIO_GROUP_SCOPE_NAME = `${RADIO_SCOPE_NAME}Group`;

export const RADIO_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${RADIO_SCOPE_NAME}`;
export const RADIO_LABEL_CLASSNAME = `${RADIO_ROOT_CLASSNAME}-label`;
export const RADIO_BASE_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${RADIO_BASE_SCOPE_NAME}`;
export const RADIO_GROUP_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${RADIO_GROUP_SCOPE_NAME}`;
export const RADIO_GROUP_LABEL_CLASSNAME = `${RADIO_GROUP_CLASSNAME}-label`;
export const RADIO_GROUP_BODY_CLASSNAME = `${RADIO_GROUP_CLASSNAME}-body`;
