import { GLOBALS } from '../../../core/src';

export const RADIO_SCOPE_NAME = 'Radio';
export const RADIO_ELEMENT_SCOPE_NAME = `${RADIO_SCOPE_NAME}Element`;

export const RADIO_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${RADIO_SCOPE_NAME}`;
export const RADIO_LABEL_CLASSNAME = `${RADIO_ROOT_CLASSNAME}-label`;
export const RADIO_ELEMENT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${RADIO_ELEMENT_SCOPE_NAME}`;
