import { GLOBALS } from '../../../core/src';

export const FORM_FIELD_SCOPE_NAME = 'FormField';

export const FORM_FIELD_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${FORM_FIELD_SCOPE_NAME}`;
export const FORM_FIELD_LABEL_CLASSNAME = `${FORM_FIELD_ROOT_CLASSNAME}-label`;
export const FORM_FIELD_INPUT_CLASSNAME = `${FORM_FIELD_ROOT_CLASSNAME}-input`;
export const FORM_FIELD_MESSAGE_CLASSNAME = `${FORM_FIELD_ROOT_CLASSNAME}-message`;
