export const BUTTON_SCOPE_NAME = 'Button';
export const BUTTON_FULLWIDTH_CLASSNAME = `${BUTTON_SCOPE_NAME}--fullwidth`;
export const BUTTON_TEXT_CLASSNAME = `${BUTTON_SCOPE_NAME}-text`;
export const BUTTON_PRELOADER_CLASSNAME = `${BUTTON_SCOPE_NAME}-preloader`;
export const BUTTON_ICON_CLASSNAME = `${BUTTON_SCOPE_NAME}-icon`;
export const BUTTON_ICON_BEFORE_CLASSNAME = `${BUTTON_ICON_CLASSNAME}--before`;
export const BUTTON_ICON_AFTER_CLASSNAME = `${BUTTON_ICON_CLASSNAME}--after`;
