import { GLOBALS } from '../../../core/src';

export const TEXT_INPUT_SCOPE_NAME = 'TextInput';
export const TEXT_INPUT_BASE_SCOPE_NAME = `${TEXT_INPUT_SCOPE_NAME}Base`;

export const TEXT_INPUT_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${TEXT_INPUT_SCOPE_NAME}`;
export const TEXT_INPUT_BASE_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${TEXT_INPUT_BASE_SCOPE_NAME}`;
export const TEXT_INPUT_BASE_MULTILINE_CLASSNAME = `${TEXT_INPUT_BASE_CLASSNAME}--multiline`;
export const TEXT_INPUT_CONTROL_CLASSNAME = `${TEXT_INPUT_ROOT_CLASSNAME}-control`;
export const TEXT_INPUT_ADORNMENT_CLASSNAME = `${TEXT_INPUT_ROOT_CLASSNAME}-adornment`;
export const TEXT_INPUT_ADORNMENT_START_CLASSNAME = `${TEXT_INPUT_ADORNMENT_CLASSNAME}-start`;
export const TEXT_INPUT_ADORNMENT_END_CLASSNAME = `${TEXT_INPUT_ADORNMENT_CLASSNAME}-end`;
export const TEXT_INPUT_WITH_ADORNMENT_START_CLASSNAME = `${TEXT_INPUT_ROOT_CLASSNAME}-withStartAdornment`;
export const TEXT_INPUT_WITH_ADORNMENT_END_CLASSNAME = `${TEXT_INPUT_ROOT_CLASSNAME}-withEndAdornment`;
