import { GLOBALS } from '../../../core/src';

export const TEXT_INPUT_SCOPE_NAME = 'TextInput';
export const TEXT_INPUT_ELEMENT_SCOPE_NAME = `${TEXT_INPUT_SCOPE_NAME}Element`;

export const TEXT_INPUT_ROOT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${TEXT_INPUT_SCOPE_NAME}`;
export const TEXT_INPUT_ELEMENT_CLASSNAME = `${GLOBALS.COMPONENT_CLASSNAME_PREFIX}${TEXT_INPUT_ELEMENT_SCOPE_NAME}`;
export const TEXT_INPUT_ELEMENT_MULTILINE_CLASSNAME = `${TEXT_INPUT_ELEMENT_CLASSNAME}--multiline`;
